name: Run radical tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build docker image
      run: docker build -t radical .
    - name: Run tests
      run: docker run --rm -v $(pwd):/var/app -e 'RADICAL_ENV=test' radical
